version: '3'
services:
  dev:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        USER: vscode
        USER_ID: ${USER_ID:-1000}
        USER_GID: ${USER_GID:-1000}
    volumes:
      - ..:/workspace:cached
      - hello-as-nix:/nix
      - hello-as-vscode-extensions:/home/vscode/.vscode-server/extensions
    security_opt:
      - label:disable
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  hello-as-nix:
  hello-as-vscode-extensions: